version: "3.8"

services:
  client:
    image: client-prod-i

    build:
      dockerfile: Dockerfile.prod

    ports:
      - "80:80"
    environment:
      - REACT_APP_NODE_ENV=production

  server:
    image: server-prod-image
    build:
      dockerfile: Dockerfile.prod

    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
