version: "3.8"

services:
  client:
    build:
      context: ./frontend
  server:
    build:
      context: ./backend
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: yelp

    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: yelp
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
